//! Guest ELF binary constants.
//!
//! After building guest programs with the appropriate zkVM toolchain,
//! the compiled ELF binaries are referenced here for use by the prover.
//!
//! # Build Instructions
//!
//! ## SP1
//!
//! ```bash
//! # Install SP1 toolchain
//! curl -L https://sp1.succinct.xyz | bash
//! sp1up
//!
//! # Build range proof guest (Ethereum DA)
//! cd guests/range-ethereum/sp1
//! cargo prove build --features sp1
//! ```
//!
//! ## RISC Zero
//!
//! ```bash
//! # Install RISC Zero toolchain
//! curl -L https://risczero.com/install | bash
//! rzup install
//!
//! # Build via risc0-build (recommended)
//! cargo build -p open-zk-build-risc0 --features rebuild-guest,debug-guest-build
//! ```

// ---------------------------------------------------------------------------
// DA-specific range proof guest ELF paths (SP1)
// ---------------------------------------------------------------------------

/// Path to the Ethereum DA range proof guest ELF (SP1 v6).
pub const RANGE_ETHEREUM_ELF_PATH: &str =
    "guests/range-ethereum/sp1/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-ethereum-sp1";

/// Path to the Celestia DA range proof guest ELF (SP1 v6).
pub const RANGE_CELESTIA_ELF_PATH: &str =
    "guests/range-celestia/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-celestia";

/// Path to the EigenDA range proof guest ELF (SP1 v6).
pub const RANGE_EIGENDA_ELF_PATH: &str =
    "guests/range-eigenda/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-eigenda";

/// Path to the aggregation guest ELF (SP1 v6).
pub const AGGREGATION_ELF_PATH: &str =
    "guests/aggregation/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-aggregation";

// ---------------------------------------------------------------------------
// Compile-time ELF include macros (SP1)
// ---------------------------------------------------------------------------

/// Include the Ethereum DA range proof ELF at compile time.
#[macro_export]
macro_rules! include_range_ethereum_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/range-ethereum/sp1/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-ethereum-sp1"
        ))
    };
}

/// Include the Celestia DA range proof ELF at compile time.
#[macro_export]
macro_rules! include_range_celestia_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/range-celestia/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-celestia"
        ))
    };
}

/// Include the EigenDA range proof ELF at compile time.
#[macro_export]
macro_rules! include_range_eigenda_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/range-eigenda/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-eigenda"
        ))
    };
}

/// Include the aggregation ELF at compile time.
#[macro_export]
macro_rules! include_aggregation_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/aggregation/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-aggregation"
        ))
    };
}

// ---------------------------------------------------------------------------
// RISC Zero ELF and image ID (via risc0-build)
// ---------------------------------------------------------------------------

/// Re-exports from the risc0 build crate.
/// These constants are generated by `risc0-build::embed_methods_with_options()`.
#[cfg(feature = "risc0")]
pub mod risc0 {
    pub use open_zk_build_risc0::GUEST_RANGE_ETHEREUM_RISC0_ELF;
    pub use open_zk_build_risc0::GUEST_RANGE_ETHEREUM_RISC0_ID;
}
