//! Guest ELF binary constants.
//!
//! After building guest programs with the appropriate zkVM toolchain,
//! the compiled ELF binaries are referenced here for use by the prover.
//!
//! # Build Instructions
//!
//! ## SP1 (recommended)
//!
//! ```bash
//! # Install SP1 toolchain
//! curl -L https://sp1.succinct.xyz | bash
//! sp1up
//!
//! # Build range proof guest
//! cd guests/range
//! cargo prove build --features sp1
//!
//! # Build aggregation guest
//! cd guests/aggregation
//! cargo prove build --features sp1
//! ```
//!
//! ## RISC Zero
//!
//! ```bash
//! # Install RISC Zero toolchain
//! curl -L https://risczero.com/install | bash
//! rzup install
//!
//! # Build range proof guest
//! cd guests/range
//! cargo risczero build --features risczero
//!
//! # Build aggregation guest
//! cd guests/aggregation
//! cargo risczero build --features risczero
//! ```
//!
//! # Automated Build
//!
//! When building with SP1, you can use `sp1-build` in the host crate's `build.rs`
//! to compile guests automatically:
//!
//! ```rust,ignore
//! // build.rs
//! use sp1_build::build_program;
//! fn main() {
//!     build_program("../../guests/range");
//!     build_program("../../guests/aggregation");
//! }
//! ```

// ---------------------------------------------------------------------------
// DA-specific range proof guest ELF paths
// ---------------------------------------------------------------------------

/// Path to the Ethereum DA range proof guest ELF (SP1 v6).
pub const RANGE_ETHEREUM_ELF_PATH: &str =
    "guests/range-ethereum/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-ethereum";

/// Path to the Celestia DA range proof guest ELF (SP1 v6).
pub const RANGE_CELESTIA_ELF_PATH: &str =
    "guests/range-celestia/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-celestia";

/// Path to the EigenDA range proof guest ELF (SP1 v6).
pub const RANGE_EIGENDA_ELF_PATH: &str =
    "guests/range-eigenda/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-eigenda";

/// Path to the generic range proof guest ELF (SP1 v6, legacy skeleton).
pub const RANGE_ELF_PATH: &str =
    "guests/range/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range";

/// Path to the aggregation guest ELF (SP1 v6).
pub const AGGREGATION_ELF_PATH: &str =
    "guests/aggregation/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-aggregation";

// ---------------------------------------------------------------------------
// Compile-time ELF include macros
// ---------------------------------------------------------------------------

/// Include the Ethereum DA range proof ELF at compile time.
#[macro_export]
macro_rules! include_range_ethereum_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/range-ethereum/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-ethereum"
        ))
    };
}

/// Include the Celestia DA range proof ELF at compile time.
#[macro_export]
macro_rules! include_range_celestia_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/range-celestia/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-celestia"
        ))
    };
}

/// Include the EigenDA range proof ELF at compile time.
#[macro_export]
macro_rules! include_range_eigenda_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/range-eigenda/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range-eigenda"
        ))
    };
}

/// Include the generic range proof ELF at compile time (legacy skeleton).
#[macro_export]
macro_rules! include_range_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/range/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-range"
        ))
    };
}

/// Include the aggregation ELF at compile time.
#[macro_export]
macro_rules! include_aggregation_elf {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../guests/aggregation/target/elf-compilation/riscv64im-succinct-zkvm-elf/release/guest-aggregation"
        ))
    };
}

// ---------------------------------------------------------------------------
// RISC Zero ELF and image ID (via risc0-build)
// ---------------------------------------------------------------------------

/// Re-exports from the risc0 build crate.
/// These constants are generated by `risc0-build::embed_methods_with_options()`.
#[cfg(feature = "risczero")]
pub mod risczero {
    pub use open_zk_build_risczero::GUEST_RANGE_ETHEREUM_ELF;
    pub use open_zk_build_risczero::GUEST_RANGE_ETHEREUM_ID;
}
