mod prover;
mod witness;

pub use prover::{RiscZeroProgram, RiscZeroProverBackend, RiscZeroProverError};
pub use witness::{RiscZeroWitness, raw_witness_to_risc0_witness};

/// Re-exports from the risc0 build crate.
/// These constants are generated by `risc0-build::embed_methods_with_options()`.
#[cfg(feature = "rebuild-guest")]
pub mod elf {
    pub use open_zk_build_risc0::GUEST_RANGE_ETHEREUM_RISC0_ELF;
    pub use open_zk_build_risc0::GUEST_RANGE_ETHEREUM_RISC0_ID;
}
